language: clojure
lein: lein
script: lein all test
jdk:
  - openjdk11
  - openjdk14
  - openjdk-ea
  - oraclejdk11
  - oraclejdk14
  - oraclejdk-ea
after_script:
  - lein cloverage -o cov --coveralls && curl -F 'json_file=@cov/coveralls.json' 'https://coveralls.io/api/v1/jobs'
