language: clojure
lein: lein
script: lein all test
jdk:
  - openjdk8
  - oraclejdk7
  - oraclejdk8
after_script:
  - lein cloverage -o cov --coveralls && curl -F 'json_file=@cov/coveralls.json' 'https://coveralls.io/api/v1/jobs'
